//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetploegApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Earthquake : Measurement
    {
        public byte VictimsState { get; set; }
        public byte BuildingsState { get; set; }
        public byte InfrastructureState { get; set; }
        public string VictimDetails { get; set; }
        public string BuildingDetails { get; set; }
        public string InfrastructureDetails { get; set; }
    }
}
