//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetploegApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasMeasurement : Measurement
    {
        public double LelResult { get; set; }
        public int PumpStrokes { get; set; }
        public System.DateTime FirstPumpStroke { get; set; }
        public double Concentration { get; set; }
        public double CoMeasurement { get; set; }
        public int GasTubeCode { get; set; }
    }
}
