//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetploegApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GpsLocation
    {
        public int Id { get; set; }
        public int MeasuringTeamId { get; set; }
        public int IncidentId { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual MeasuringTeam MeasuringTeam { get; set; }
        public virtual Incident Incident { get; set; }
    }
}
