//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetploegApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureAssignment : Assignment
    {
        public int GastubeCode { get; set; }
        public bool LelMeasurement { get; set; }
        public bool Automess { get; set; }
        public bool AutomessProbe { get; set; }
        public bool DoseMeasurer { get; set; }
        public bool BreathableAir { get; set; }
    }
}
