//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetploegApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int Id { get; set; }
        public int AssignmentId { get; set; }
        public string MeasurementType { get; set; }
        public string Observations { get; set; }
        public System.DateTime MeasurementTime { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    
        public virtual Assignment Assignment { get; set; }
    }
}
