//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetploegApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VGRDataModelContainer : DbContext
    {
        public VGRDataModelContainer()
            : base("name=VGRDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Incident> IncidentSet { get; set; }
        public virtual DbSet<Assignment> AssignmentSet { get; set; }
        public virtual DbSet<MeasuringTeam> MeasuringTeamSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Message> MessageSet { get; set; }
        public virtual DbSet<MessageToUser> MessageToUserSet { get; set; }
        public virtual DbSet<Measurement> MeasurementSet { get; set; }
        public virtual DbSet<GpsLocation> GpsLocationSet { get; set; }
    }
}
